# Contours: OpenCV

Contours in image processing refer to the boundaries or outlines of objects within an image. They are a fundamental concept in computer vision and are widely used for various tasks, including object detection, object recognition, shape analysis, and image segmentation. Contours help in identifying and extracting the shapes and structures present in an image.

Here are some key points about contours:

1. **Definition**: A contour is a curve or a boundary that connects the continuous points of an object having the same color or intensity. In simpler terms, it represents the shape of an object within an image.

2. **Representation**: Contours are typically represented as a list of coordinates (x, y) that define the contour's shape. OpenCV, a popular computer vision library, represents contours as a list of points.

3. **Hierarchy**: In some cases, images may contain nested or hierarchical contours. For example, when one object is contained within another, a parent-child relationship exists between the contours. OpenCV provides methods to extract and analyze hierarchical contours.

4. **Use Cases**:
   - **Object Detection**: Contours can be used to identify and locate objects within an image. By finding contours, you can determine the position, size, and shape of objects.
   - **Shape Analysis**: Contours enable shape-based analysis, which can be used to classify and recognize objects based on their shapes.
   - **Image Segmentation**: Contours are used to separate objects from the background or from each other in image segmentation tasks.
   - **Region of Interest (ROI) Extraction**: Contours can be used to define regions of interest within an image for further analysis.

Here's a simplified example of how to find and draw contours in an image using OpenCV in Python:

```python
import cv2
import numpy as np

# Read an image
image = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)

# Find contours in the image
contours, _ = cv2.findContours(image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Draw the contours on a copy of the original image
contour_image = np.copy(image)
cv2.drawContours(contour_image, contours, -1, (0, 255, 0), 2)

# Display the original image with contours
cv2.imshow('Original Image', image)
cv2.imshow('Image with Contours', contour_image)

# Wait for a key press and close the windows
cv2.waitKey(0)
cv2.destroyAllWindows()
```

In this example, we read an image, find its contours using `cv2.findContours()`, and then draw the contours on a copy of the original image. The `cv2.RETR_EXTERNAL` flag specifies that only the outermost (external) contours should be considered, and `cv2.CHAIN_APPROX_SIMPLE` specifies a simple contour representation.

Contours are a versatile and powerful tool in image processing and computer vision, enabling a wide range of applications for analyzing and understanding the content of images.

In [1]:
import cv2
import numpy as np

# Read an image
image = cv2.imread('Images/logo.jpg', cv2.IMREAD_GRAYSCALE)
image=cv2.resize(image,(500,500))

# Find contours in the image
contours, _ = cv2.findContours(image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Draw the contours on a copy of the original image
contour_image = np.copy(image)
cv2.drawContours(contour_image, contours, -1, (0, 255, 0), 2)

# Display the original image with contours
cv2.imshow('Original Image', image)
cv2.imshow('Image with Contours', contour_image)

# Wait for a key press and close the windows
cv2.waitKey(0)
cv2.destroyAllWindows()


In [1]:
#Contours - 
#Contours can be explained simply as a curve joining all the continuous points 
#(along the boundary), having same color or intensity. 

#The contours are a useful tool for shape analysis and object detection and recognition

#For better accuracy, use binary images and also apply edge detection before 
#finding countours.

#findCountour function manipulate original imge so copy it before proceeding.
#findContour is like finding white object from black background.
#so you must turn image in white and background is black.

#We have to find and draw contours as per the requirement.

import cv2
import numpy as np
img = cv2.imread("Images/logo.jpg")
img1 = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(img1,127,255,0)
#findcontour(img,contour_retrival_mode,method)
cnts,hier = cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
#Here cnts is a list of contours. ANd each contour is an array with x, y cordinate   
#hier variable called hierarchy and it contain image information.
print("Number of contour==",cnts,"\ntotal contour==",len(cnts))
print("Hierarchy==\n",hier)

#drawcontour(img,cnts,id of contour,color,thickness)#here if we draw all
#contour just pass -1
#Draw the contours
img = cv2.drawContours(img,cnts,-1,(176,10,15),4)


#ouput----
cv2.imshow("original===",img)
cv2.imshow("gray==",img1)
cv2.imshow("thresh==",thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()



Number of contour== (array([[[213, 256]]], dtype=int32), array([[[ 88, 227]],

       [[ 87, 228]],

       [[ 85, 228]],

       [[ 85, 231]],

       [[ 84, 232]],

       [[ 83, 231]],

       [[ 84, 232]],

       [[ 84, 233]],

       [[ 83, 234]],

       [[ 83, 249]],

       [[ 84, 250]],

       [[ 84, 251]],

       [[ 83, 252]],

       [[ 84, 251]],

       [[ 85, 252]],

       [[ 85, 254]],

       [[ 86, 255]],

       [[ 86, 256]],

       [[ 87, 256]],

       [[ 88, 255]],

       [[ 89, 256]],

       [[ 91, 256]],

       [[ 92, 257]],

       [[101, 257]],

       [[102, 256]],

       [[105, 256]],

       [[106, 255]],

       [[107, 256]],

       [[107, 255]],

       [[108, 254]],

       [[108, 253]],

       [[109, 252]],

       [[110, 252]],

       [[110, 247]],

       [[104, 247]],

       [[102, 249]],

       [[102, 250]],

       [[101, 251]],

       [[ 98, 251]],

       [[ 97, 250]],

       [[ 96, 251]],

       [[ 94, 251]],

       [[ 92, 249]]

# Properties

Contours in OpenCV have several properties or attributes that can be accessed and used for various image processing and computer vision tasks. Below are some of the key properties and methods associated with contours:

1. **Coordinates**: Contours are represented as lists of points, where each point is a tuple (x, y) representing the coordinates of a contour point.

2. **Area**: You can calculate the area enclosed by a contour using the `cv2.contourArea()` function. This property is useful for tasks like object size estimation.

3. **Perimeter**: The perimeter or circumference of a contour can be calculated using the `cv2.arcLength()` function. This is helpful for shape analysis and detecting irregularities.

4. **Bounding Box**: You can obtain the bounding box around a contour using `cv2.boundingRect()`. This returns a tuple representing the (x, y) coordinates of the top-left corner of the bounding box and its width and height.

5. **Bounding Circle**: The minimum enclosing circle around a contour can be calculated using `cv2.minEnclosingCircle()`. This gives you the center and radius of the circle.

6. **Convex Hull**: The convex hull of a contour is the smallest convex shape that encloses the contour. You can find the convex hull using `cv2.convexHull()`.

7. **Moments**: Moments provide statistical information about the contour's shape, including its centroid, area, and various shape descriptors. Use `cv2.moments()` to compute moments.

8. **Approximation**: You can approximate a contour with a simpler shape (e.g., a polygon) using functions like `cv2.approxPolyDP()`.

9. **Hierarchy**: When multiple contours exist in an image, the hierarchy represents their relationships. The hierarchy information can be retrieved using `cv2.findContours()` with the `cv2.RETR_TREE` or `cv2.RETR_CCOMP` retrieval modes.

10. **Drawing**: Contours can be drawn on an image using `cv2.drawContours()`, which allows you to specify the color, thickness, and whether to draw all contours or specific ones.

11. **Filtering**: You can filter contours based on their area, aspect ratio, or other criteria to select the ones of interest for further analysis.

12. **Centroid**: The centroid of a contour can be calculated using the moments. It represents the center of mass of the contour.

Here's an example that demonstrates some of these contour properties:

```python
import cv2

# Read an image
image = cv2.imread('input.jpg', cv2.IMREAD_GRAYSCALE)

# Find contours
contours, _ = cv2.findContours(image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Iterate through contours
for contour in contours:
    # Calculate and print contour properties
    area = cv2.contourArea(contour)
    perimeter = cv2.arcLength(contour, True)
    bounding_box = cv2.boundingRect(contour)
    convex_hull = cv2.convexHull(contour)
    
    print(f"Area: {area}, Perimeter: {perimeter}")
    print(f"Bounding Box: {bounding_box}")
    print(f"Convex Hull: {convex_hull}")

    # Draw the contour and its bounding box
    cv2.drawContours(image, [contour], -1, (0, 255, 0), 2)
    x, y, w, h = bounding_box
    cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)

# Display the image with contours and bounding boxes
cv2.imshow('Image with Contours', image)

# Wait for a key press and close the window
cv2.waitKey(0)
cv2.destroyAllWindows()
```

In this example, we find contours in an image and calculate various properties such as area, perimeter, bounding box, and convex hull for each contour. The properties are printed, and the contours and bounding boxes are drawn on the image for visualization.

In [3]:
import cv2

# Read an image
image = cv2.imread('Images/hand.jpg', cv2.IMREAD_GRAYSCALE)
image=cv2.resize(image,(500,500))

# Find contours
contours, _ = cv2.findContours(image, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Iterate through contours
for contour in contours:
    # Calculate and print contour properties
    area = cv2.contourArea(contour)
    perimeter = cv2.arcLength(contour, True)
    bounding_box = cv2.boundingRect(contour)
    convex_hull = cv2.convexHull(contour)
    
    print(f"Area: {area}, Perimeter: {perimeter}")
    print(f"Bounding Box: {bounding_box}")
    print(f"Convex Hull: {convex_hull}")

    # Draw the contour and its bounding box
    cv2.drawContours(image, [contour], -1, (0, 255, 0), 2)
    x, y, w, h = bounding_box
    cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)

# Display the image with contours and bounding boxes
cv2.imshow('Image with Contours', image)

# Wait for a key press and close the window
cv2.waitKey(0)
cv2.destroyAllWindows()


Area: 249001.0, Perimeter: 1996.0
Bounding Box: (0, 0, 500, 500)
Convex Hull: [[[499   0]]

 [[499 499]]

 [[  0 499]]

 [[  0   0]]]


In [1]:
import cv2
import numpy as np

img = cv2.imread("Images/hand.jpg")
img = cv2.resize(img,(600,700))
img1 = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

blur = cv2.medianBlur(img1,11)

ret,thresh = cv2.threshold(blur,240,255,cv2.THRESH_BINARY_INV)
dilata = cv2.dilate(thresh,(1,1),iterations = 6)
#findcontour(img,contour_retrival_mode,method)
cnts,hier = cv2.findContours(thresh,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
#Here cnts is a list of contours. ANd each contour is an array with x, y cordinate   
#hier variable called hierarchy and it contain image information.
print("Number of contour==",cnts,"\ntotal contour==",len(cnts))
print("Hierarchy==\n",hier)

# loop over the contours
for c in cnts:
    epsilon = 0.0001*cv2.arcLength(c,True)
    data= cv2.approxPolyDP(c,epsilon,True)
    
    hull = cv2.convexHull(data)
    
    
    cv2.drawContours(img, [c], -1, (50, 50, 150), 2)
    cv2.drawContours(img, [hull], -1, (0, 255, 0), 2)

#find convexity defect
hull2 = cv2.convexHull(cnts[0],returnPoints = False)
#defect returns an array which contain value  [start_point, end_point, farthest_point, approximate_distance to farthest point ]
defect = cv2.convexityDefects(cnts[0],hull2)

for i in range(defect.shape[0]):
    s,e,f,d = defect[i,0]
    print(s,e,f,d)
    start = tuple(c[s][0])
    end = tuple(c[e][0])
    far = tuple(c[f][0])
    #cv2.line(img,start,end,[255,0,0],2)
    cv2.circle(img,far,5,[0,0,255],-1)
    

  
#Extreme Points----
#It means topmost, bottommost, rightmost and leftmost points of the object.

c_max = max(cnts, key=cv2.contourArea)

# determine the most extreme points along the contour
extLeft = tuple(c_max[c_max[:, :, 0].argmin()][0])
extRight = tuple(c_max[c_max[:, :, 0].argmax()][0])
extTop = tuple(c_max[c_max[:, :, 1].argmin()][0])
extBot = tuple(c_max[c_max[:, :, 1].argmax()][0])

# draw the outline of the object, then draw each of the
# extreme points, where the left-most is red, right-most
# is green, top-most is blue, and bottom-most is teal

cv2.circle(img, extLeft, 8, (255, 0, 255), -1)  #pink
cv2.circle(img, extRight, 8, (0, 125, 255), -1) #brown
cv2.circle(img, extTop, 8, (255, 10, 0), -1)  #blue
cv2.circle(img, extBot, 8, (19, 152, 152), -1) #green


cv2.imshow("original===",img)
cv2.imshow("gray==",img1)
cv2.imshow("thresh==",thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

Number of contour== (array([[[334,  38]],

       [[333,  39]],

       [[332,  39]],

       ...,

       [[348,  39]],

       [[346,  39]],

       [[345,  38]]], dtype=int32),) 
total contour== 1
Hierarchy==
 [[[-1 -1 -1 -1]]]
0 150 53 57130
150 152 151 162
152 156 153 114
157 333 244 46157
333 339 334 114
339 341 340 186
342 344 343 186
344 346 345 114
346 522 435 25202
523 525 524 162
525 641 538 4368
641 651 642 229
651 653 652 186
653 793 696 3360
794 796 795 162
796 800 797 114
801 1003 940 49907
1003 1005 1004 154
1005 1011 1006 114
1011 1087 1046 52894
1087 1089 1088 162
